/aruco_detector:
  ros__parameters:
    aruco_side: 0.15
    autostart: true
    subscriber_best_effot_qos: true
    subscriber_depth: 1
    subscriber_transport: raw
    valid_ids:
      - 15
      - 23
    worker_cpu: -1
