/aruco_detector:
  ros__parameters:
    always_publish_stream: false
    aruco_side: 0.15
    autostart: true
    dictionary: DICT_ARUCO_ORIGINAL
    subscriber_base_topic_name: /camera/image_rect_color
    subscriber_best_effort_qos: true
    subscriber_depth: 1
    subscriber_transport: raw
    valid_ids:
      - 15
      - 23
    worker_cpu: -1
