header_include_path: aruco_detector/aruco_detector.hpp
namespace: ArucoDetector
node_class_name: ArucoDetectorNode

params:
  aruco_side:
    type: double
    default_value: 0.1
    min_value: 0.0
    max_value: 2.0
    step: 0.0
    description: "ArUco marker side in meters."
    constraints: "Cannot be changed."
    read_only: true
    var_name: aruco_side_

  autostart:
    type: bool
    default_value: false
    description: "Whether to start detection immediately."
    constraints: "Cannot be changed."
    read_only: true
    var_name: autostart_

  best_effort_sub_qos:
    type: bool
    default_value: false
    description: "Whether to subscribe to the input topics with a best effort QoS."
    constraints: "Cannot be changed."
    read_only: true
    var_name: best_effort_sub_qos_

  image_sub_depth:
    type: integer
    default_value: 1
    min_value: 0
    max_value: 100
    step: 1
    description: "Image subscriber queue depth."
    constraints: "Cannot be changed."
    read_only: true
    var_name: image_sub_depth_

  transport:
    type: string
    default_value: raw
    description: "Transport type to use with image_transport."
    constraints: "Cannot be changed."
    read_only: true
    var_name: transport_

  valid_ids:
    type: integer_array
    default_value: [0]
    min_value: 0
    max_value: 10000
    step: 1
    description: "List of valid Arucos."
    constraints: "Cannot be changed."
    read_only: false
    var_name: valid_ids_

  worker_cpu:
    type: integer
    default_value: -1
    min_value: -1
    max_value: 255
    step: 1
    description: "CPU on which the worker will be pinned."
    constraints: "Cannot be changed, -1 disables this policy."
    read_only: true
    var_name: worker_cpu_
