header_include_path: aruco_detector/aruco_detector.hpp
namespace: aruco_detector
node_class_name: ArucoDetector

params:
  aruco_side:
    type: double
    default_value: 0.1
    min_value: 0.0
    max_value: 2.0
    step: 0.0
    description: "ArUco marker side [m]."
    constraints: "Cannot be changed."
    read_only: true
    var_name: aruco_side_

  autostart:
    type: bool
    default_value: false
    description: "Start detection right after node initialization."
    constraints: "Cannot be changed."
    read_only: true

  dictionary:
    type: string
    default_value: DICT_ARUCO_ORIGINAL
    description: "ArUco dictionary to use."
    constraints: "Cannot be changed, must be the name of one of the values in the cv::aruco::PredefinedDictionaryType enum."
    read_only: true
    validator: validate_dictionary

  subscriber_base_topic_name:
    type: string
    default_value: /camera/image_rect_color
    description: "Base name of the input topics family to be passed to image_transport APIs."
    constraints: "Cannot be changed."
    read_only: true

  subscriber_best_effort_qos:
    type: bool
    default_value: true
    description: "Whether to subscribe to the input topic with a best effort QoS."
    constraints: "Cannot be changed."
    read_only: true

  subscriber_depth:
    type: integer
    default_value: 1
    min_value: 0
    max_value: 100
    step: 1
    description: "Image subscriber queue depth."
    constraints: "Cannot be changed."
    read_only: true

  subscriber_transport:
    type: string
    default_value: raw
    description: "Transport type to use with image_transport."
    constraints: "Cannot be changed."
    read_only: true

  valid_ids:
    type: integer_array
    default_value: [0]
    min_value: 0
    max_value: 10000
    step: 1
    description: "List of valid Arucos."
    constraints: "Cannot be changed."
    read_only: false
    var_name: valid_ids_

  worker_cpu:
    type: integer
    default_value: -1
    min_value: -1
    max_value: 255
    step: 1
    description: "CPU on which the worker thread will be pinned."
    constraints: "Cannot be changed, -1 disables this policy."
    read_only: true
    var_name: worker_cpu_
